name: CMake

on:
  push:
    branches: lab04_hw

jobs:
  formatter:
    runs-on: ubuntu-latest
    env:
      PATH_F: ${{github.workspace}}/homework/lab04/formatter_lib
    steps:
    - uses: actions/checkout@v3
    - name: Build formatter
      run: cmake -S${{env.PATH_F}} -B${{env.PATH_F}}/_build
    - run: cmake --build ${{env.PATH_F}}/_build
  formatter_ex:
    runs-on: ubuntu-latest
    env:
      PATH_FX: ${{github.workspace}}/homework/lab04/formatter_ex_lib
    steps:
    - uses: actions/checkout@v3
    - name: Build formatter_ex
      run: cmake -S${{env.PATH_FX}} -B${{env.PATH_FX}}/_build
    - run: cmake --build ${{env.PATH_FX}}/_build
  hello_world:
    runs-on: ubuntu-latest
    env:
      PATH_H: ${{github.workspace}}/homework/lab04/hello_world_application
    steps:
    - uses: actions/checkout@v3
    - name: Build hello_world_app
      run: cmake -S${{env.PATH_H}} -B${{env.PATH_H}}/_build
    - run: cmake --build ${{env.PATH_H}}/
  solver:
    runs-on: ubuntu-latest
    env:
      PATH_S: ${{github.workspace}}/homework/lab04/solver_application
    steps:
    - uses: actions/checkout@v3
    - name: Build solver_app
      run: cmake -S${{env.PATH_S}} -B${{env.PATH_S}}/_build
    - run: cmake --build ${{env.PATH_S}}/_build
