name: CMake

on:
  push:
    branches: lab04_hw

env:
  SHORT_PATH: ${{github.workspace}}/homework/lab04

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Build formatter
      run: cmake -S${{env.SHORT_PATH}} -B${{env.SHORT_PATH}}/_formatter_lib/build
    - run: cmake --build ${{env.SHORT_PATH}}/formatter_lib/_build

    - name: Build formatter_ex
      run: cmake -S${{env.SHORT_PATH}} -B${{env.SHORT_PATH}}/formatter_ex_lib/_build
    - run: cmake --build ${{env.SHORT_PATH}}/formatter_ex_lib/_build

    - name: Build hello_world_app
      run: cmake -S${{env.SHORT_PATH}} -B${{env.SHORT_PATH}}/hello_world_application/_build
    - run: cmake --build ${{env.SHORT_PATH}}/hello_world_application/

    - name: Build solver_app
      run: cmake -S${{env.SHORT_PATH}} -B${{env.SHORT_PATH}}/solver_application/_build
    - run: cmake --build ${{env.SHORT_PATH}}/solver_application/_build
